version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - DEEPFINDAI_LICENSE_KEY=${DEEPFINDAI_LICENSE_KEY}
    restart: unless-stopped

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    restart: unless-stopped

  sandbox:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./sandbox:/app
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - DEEPFINDAI_LICENSE_KEY=${DEEPFINDAI_LICENSE_KEY}
    restart: unless-stopped

networks:
  dfw-network:
    driver: bridge

volumes:
  frontend-data:
  backend-data:
  vectordb-data: 